/**
 * AUTO-GENERATED by scripts/generate-design-tokens.mjs.
 * Source: design-tokens/stylee-v3.8.tokens.json
 *
 * Do not edit this file directly. Update the Tokens Studio source and run:
 * npm run tokens:build
 */
export const ds = {
  "meta": {
    "name": "Stylee Design System",
    "version": "3.8.0"
  },
  "color": {
    "primitive": {
      "neutral0": "#FFFFFF",
      "neutral25": "#FAFAFA",
      "neutral50": "#F4F4F5",
      "neutral100": "#ECECEE",
      "neutral200": "#DEDEE1",
      "neutral500": "#9A9AA0",
      "neutral700": "#6B6B6E",
      "neutral900": "#1C1C1E",
      "neutral950": "#0A0A0A",
      "oxblood100": "#F2EDEA",
      "oxblood700": "#7F3A34",
      "moss100": "#EFF1EC",
      "moss700": "#555F50",
      "brandCream": "#F5EDE2",
      "brandCocoa": "#2A1810"
    },
    "semantic": {
      "surface": {
        "base": "#FFFFFF",
        "card": "#FAFAFA",
        "input": "#F4F4F5",
        "floating": "#FFFFFF",
        "inverse": "#0A0A0A"
      },
      "text": {
        "primary": "#0A0A0A",
        "secondary": "#6B6B6E",
        "tertiary": "#9A9AA0",
        "inverse": "#FFFFFF",
        "accent": "#7F3A34",
        "positive": "#555F50"
      },
      "border": {
        "subtle": "#F4F4F5",
        "default": "#ECECEE",
        "strong": "#DEDEE1",
        "focus": "#0A0A0A"
      },
      "action": {
        "primary": "#0A0A0A",
        "primaryPressed": "#1C1C1E",
        "secondary": "#FFFFFF",
        "disabled": "#ECECEE",
        "destructive": "#7F3A34"
      },
      "status": {
        "positive": "#555F50",
        "positiveSubtle": "#EFF1EC",
        "attention": "#7F3A34",
        "attentionSubtle": "#F2EDEA",
        "neutral": "#6B6B6E",
        "neutralSubtle": "#F4F4F5"
      },
      "overlay": {
        "scrim": "rgba(10,10,10,0.40)",
        "scrimStrong": "rgba(10,10,10,0.60)"
      }
    }
  },
  "space": {
    "0": 0,
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "12": 48,
    "16": 64,
    "0.5": 2
  },
  "size": {
    "control": {
      "compact": 32,
      "small": 36,
      "minimumTouch": 44,
      "medium": 48,
      "large": 52,
      "hero": 56
    },
    "icon": {
      "xs": 12,
      "sm": 16,
      "md": 20,
      "lg": 24,
      "xl": 28,
      "xxl": 32
    }
  },
  "radius": {
    "xs": 4,
    "sm": 6,
    "md": 8,
    "lg": 10,
    "xl": 12,
    "xxl": 16,
    "xxxl": 20,
    "full": 999
  },
  "font": {
    "family": {
      "display": "Playfair Display",
      "body": "Inter",
      "cnSerifFallback": "Songti SC",
      "cnSansFallback": "PingFang SC"
    }
  },
  "typography": {
    "display": {
      "fontSize": 24,
      "lineHeight": 30,
      "letterSpacing": 0
    },
    "heading": {
      "fontSize": 18,
      "lineHeight": 24,
      "letterSpacing": 0
    },
    "content": {
      "fontSize": 15,
      "lineHeight": 22,
      "letterSpacing": 0.3
    },
    "support": {
      "fontSize": 12,
      "lineHeight": 18,
      "letterSpacing": 0.24
    }
  },
  "motion": {
    "duration": {
      "instant": "100ms",
      "fast": "160ms",
      "normal": "220ms",
      "slow": "360ms"
    },
    "easing": {
      "standard": [
        0.2,
        0,
        0,
        1
      ],
      "enter": [
        0,
        0,
        0,
        1
      ],
      "exit": [
        0.4,
        0,
        1,
        1
      ]
    }
  },
  "layout": {
    "screenPaddingCompact": 16,
    "screenPaddingRegular": 24,
    "contentMaxMobile": 428,
    "contentMaxReading": 720,
    "breakpointTablet": 600,
    "gridGap": 12,
    "sectionGap": 24
  },
  "component": {
    "button": {
      "largeHeight": 52,
      "mediumHeight": 48,
      "smallHeight": 44,
      "radius": 12,
      "horizontalPadding": 16
    },
    "choiceChip": {
      "visualMinHeight": 32,
      "minimumTouch": 44,
      "radius": 8,
      "horizontalPadding": 12,
      "verticalPadding": 4,
      "contentGap": 4,
      "groupGap": 8
    },
    "pageHeader": {
      "minimumHeight": 44,
      "horizontalPadding": 16,
      "actionSize": 44
    },
    "searchField": {
      "height": 44,
      "radius": 12,
      "horizontalPadding": 12,
      "contentGap": 8,
      "iconSize": 16
    },
    "wardrobeCard": {
      "radius": 12,
      "mediaAspectRatio": 1.333333,
      "infoMinimumHeight": 48,
      "infoHorizontalPadding": 8,
      "infoVerticalPadding": 4
    },
    "wardrobeGrid": {
      "referenceViewportWidth": 393,
      "referenceViewportHeight": 852,
      "columnsMobile": 2,
      "columnsTablet": 3,
      "visibleRowsReference": 3,
      "screenPadding": 16,
      "screenPaddingTablet": 24,
      "columnGap": 8,
      "rowGap": 8,
      "controlsGap": 8
    },
    "outfitItemCard": {
      "columnsMobile": 2,
      "columnsTablet": 3,
      "gap": 12,
      "padding": 8,
      "radius": 12,
      "mediaRadius": 10,
      "mediaAspectRatio": 1
    },
    "statusBadge": {
      "height": 20,
      "radius": 6,
      "horizontalPadding": 6,
      "mediaInset": 8
    },
    "inlineStatus": {
      "minimumHeight": 44,
      "radius": 12,
      "horizontalPadding": 16,
      "verticalPadding": 12
    },
    "stickyDecisionBar": {
      "horizontalPadding": 16,
      "topPadding": 12,
      "bottomPadding": 12,
      "actionGap": 8
    }
  }
} as const;

export const dsShadow = {
  "one": {
    "shadowColor": "#000000",
    "shadowOffset": {
      "width": 0,
      "height": 1
    },
    "shadowOpacity": 0.06,
    "shadowRadius": 3,
    "elevation": 1
  },
  "two": {
    "shadowColor": "#000000",
    "shadowOffset": {
      "width": 0,
      "height": 4
    },
    "shadowOpacity": 0.08,
    "shadowRadius": 14,
    "elevation": 4
  },
  "three": {
    "shadowColor": "#000000",
    "shadowOffset": {
      "width": 0,
      "height": 12
    },
    "shadowOpacity": 0.12,
    "shadowRadius": 32,
    "elevation": 8
  }
} as const;
