#!/usr/bin/env python3
import argparse
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
GENERATED_METRICS = ROOT / "src/data/outfitCanvasImageMetrics.generated.ts"
FIXTURES = {
    "bag": ("public/preset-items/black-backpack.png", (0.623, 0.847)),
    "hat": ("public/preset-items/baseball-cap.png", (0.847, 0.821)),
    "scarf": ("public/preset-items/beige-scarf.png", (0.773, 0.847)),
    "shoes": ("public/preset-items/womens-loafers.png", (0.701, 0.246)),
}
ASSETS = (
    "black-tshirt.png",
    "black-trousers.png",
    "beige-shorts.png",
    "a-line-skirt.png",
    "khaki-trench.png",
    "black-dress.png",
    "womens-loafers.png",
    "beige-scarf.png",
    "black-backpack.png",
)


def alpha_bbox(image: Image.Image, name: str) -> tuple[int, int, int, int]:
    assert image.format == "PNG", f"{name}: expected PNG"
    assert image.mode == "RGBA", f"{name}: expected RGBA, got {image.mode}"
    bbox = image.getchannel("A").getbbox()
    assert bbox is not None, f"{name}: no visible alpha"
    return bbox


def verify_fixture_safety(*, print_output: bool) -> None:
    for role, (relative, expected) in FIXTURES.items():
        with Image.open(ROOT / relative) as image:
            bbox = alpha_bbox(image, role)
            width = (bbox[2] - bbox[0]) / image.width
            height = (bbox[3] - bbox[1]) / image.height
        assert abs(width - expected[0]) <= 0.01, (role, width, expected[0])
        assert abs(height - expected[1]) <= 0.01, (role, height, expected[1])
        if print_output:
            print(role, round(width, 3), round(height, 3))


def collect_metrics() -> dict[str, tuple[float, float, float, float, float]]:
    metrics = {}
    for asset in ASSETS:
        with Image.open(ROOT / "public/preset-items" / asset) as image:
            bbox = alpha_bbox(image, asset)
            metrics[asset] = (
                image.width / image.height,
                bbox[0] / image.width,
                bbox[1] / image.height,
                (bbox[2] - bbox[0]) / image.width,
                (bbox[3] - bbox[1]) / image.height,
            )
    return metrics


def render_metrics(metrics: dict[str, tuple[float, float, float, float, float]]) -> str:
    lines = [
        "// Generated by scripts/check-outfit-fixture-alpha.py. Do not edit.",
        "export const PRESET_OUTFIT_IMAGE_METRICS = {",
    ]
    for asset in sorted(metrics):
        aspect, left, top, width, height = metrics[asset]
        lines.extend((
            f"  '/preset-items/{asset}': {{",
            f"    sourceAspectRatio: {aspect:.4g},",
            "    visibleBounds: { "
            f"left: {left:.4f}, top: {top:.4f}, width: {width:.4f}, height: {height:.4f} "
            "},",
            "  },",
        ))
    lines.extend(("} as const;", ""))
    return "\n".join(lines)


def print_metrics(metrics: dict[str, tuple[float, float, float, float, float]]) -> None:
    for asset in ASSETS:
        aspect, left, top, width, height = metrics[asset]
        print(
            asset,
            f"aspect={aspect:.4g}",
            f"bounds={left:.4f},{top:.4f},{width:.4f},{height:.4f}",
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify approved outfit fixture alpha and generated metrics.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write the generated preset image metrics")
    mode.add_argument("--check", action="store_true", help="fail if generated preset image metrics drift")
    args = parser.parse_args()

    verify_fixture_safety(print_output=not (args.write or args.check))
    if not (args.write or args.check):
        return 0

    metrics = collect_metrics()
    print_metrics(metrics)
    rendered = render_metrics(metrics)
    if args.write:
        GENERATED_METRICS.write_text(rendered, encoding="utf-8")
        return 0
    if not GENERATED_METRICS.is_file() or GENERATED_METRICS.read_text(encoding="utf-8") != rendered:
        print(f"generated preset metrics are missing or out of date: {GENERATED_METRICS}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
