// Generated by scripts/check-outfit-fixture-alpha.py. Do not edit.
export const PRESET_OUTFIT_IMAGE_METRICS = {
  '/preset-items/a-line-skirt.png': {
    sourceAspectRatio: 1,
    visibleBounds: { left: 0.1411, top: 0.0743, width: 0.7153, height: 0.8502 },
  },
  '/preset-items/beige-scarf.png': {
    sourceAspectRatio: 1,
    visibleBounds: { left: 0.1142, top: 0.0761, width: 0.7732, height: 0.8472 },
  },
  '/preset-items/beige-shorts.png': {
    sourceAspectRatio: 1,
    visibleBounds: { left: 0.0775, top: 0.1175, width: 0.8466, height: 0.7697 },
  },
  '/preset-items/black-backpack.png': {
    sourceAspectRatio: 1,
    visibleBounds: { left: 0.1886, top: 0.0757, width: 0.6227, height: 0.8470 },
  },
  '/preset-items/black-dress.png': {
    sourceAspectRatio: 1,
    visibleBounds: { left: 0.3111, top: 0.0764, width: 0.3757, height: 0.8466 },
  },
  '/preset-items/black-trousers.png': {
    sourceAspectRatio: 1,
    visibleBounds: { left: 0.3353, top: 0.0757, width: 0.3299, height: 0.8505 },
  },
  '/preset-items/black-tshirt.png': {
    sourceAspectRatio: 1,
    visibleBounds: { left: 0.0747, top: 0.0885, width: 0.8506, height: 0.8242 },
  },
  '/preset-items/khaki-trench.png': {
    sourceAspectRatio: 1,
    visibleBounds: { left: 0.1763, top: 0.0783, width: 0.6473, height: 0.8458 },
  },
  '/preset-items/womens-loafers.png': {
    sourceAspectRatio: 1,
    visibleBounds: { left: 0.2243, top: 0.3181, width: 0.7009, height: 0.2459 },
  },
} as const;
